const actions = {
  FETCH_EXCHANGE_RATES_REQUEST: 'FETCH_EXCHANGE_RATES_REQUEST',
  FETCH_EXCHANGE_RATES_SUCCESSFUL: 'FETCH_EXCHANGE_RATES_SUCCESSFUL',
  FETCH_EXCHANGE_RATES_ERROR: 'FETCH_EXCHANGE_RATES_ERROR',

  STOP_POLLING_TO_FETCH_EXCHANGE_RATE: 'STOP_POLLING_TO_FETCH_EXCHANGE_RATE',

  CONVERT_CURRENCY_FROM: 'CONVERT_CURRENCY_FROM',
  CONVERT_CURRENCY_TO: 'CONVERT_CURRENCY_TO',

  EXCHANGE_CURRENCY: 'EXCHANGE_CURRENCY',
};

export default actions;
